language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5

install:
    - npm install -g eclint
    - sudo pip install -r requirements.txt

script:
    - flake8
    - "sudo sh ./.travis/run_test.sh"
